config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  
  resources :carts do 
    post :terminar
  end

  scope "/admin" do
    resources :products
  end
  
  devise_for :users
  get "admin",to: "backoffice#index"
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  has_many :line_items
  has_one_attached  :image, :dependent => :destroy
  acts_as_paranoid

  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "line items present")
      throw :abort
    end
  end




end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <div class="form-group">
      <div class="input-group mb-3">
        <span class="input-group-text mb-3">Nombre</span>
        <%= form.text_field :name, class:'form-control mb-3' %>
      </div>
    
    <div class="form-group">
      <div class="input-group mb-3">
        <span class="input-group-text mb-3">description</span>
      <%= form.text_field :description, class:'form-control mb-3' %>
    </div>

    <div class="form-group">
      <div class="input-group mb-3">
        <span class="input-group-text mb-3">price</span>
      <%= form.number_field :price, class:'form-control mb-3' %>
    </div>

    <div class= "form-group mb-3 col-md-4 ">
      <% if @product.image.attached? %>
        <%= image_tag @product.image, style: "width: 150px; display: block"%>
      <%end%>

      <%= form.label :image %>
      <%= form.file_field :image, class: "form-control"%>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
    <br>


<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>
<div class="btn-group btn-group-sm " role="group">
  <%= link_to 'Show', @product, class: 'btn btn-primary' %>
  <%= link_to 'Back', products_path, class:'btn btn-success' %>
  </div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th scope="col">image</th>
      <th scope="col">name</th>
      <th scope="col">descripcion</th>
      <th scope="col">precio</th>
      <th style= "text-align: right">Acciones</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
      <%if product.image.attached? %>
        <td><%= image_tag product.image.variant(resize: "200x200")%></td>
      <%end%>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
          <td>
            <div class="btn-group btn-group" role="group">
            <%= link_to 'Show', product , class: "btn btn-outline-dark btn-sm"%>
            <%= link_to 'Edit', edit_product_path(product),class: "btn btn-outline-success btn-sm"%>
            <%= link_to 'Destroy', product, method: :delete, class: "btn btn-outline-danger btn-sm"%>
          </td>
        </div>
        <td>
      </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class:"btn btn-success" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <% if @product.image.attached? %>
    <div class="card mb-3" style="max-width: 440px;">
      <div class="row g-0">
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-text"><h5><b>Nombre del producto:</h5></b> <%= @product.name %>
            <p>
                <%= image_tag @product.image.variant(resize: "400x400")%>
            </p>
            <p class="card-text"><b>Descripción: </b><br><%= @product.description %></p>
            <p class="card-text"><b>Precio</b> $<%= @product.price %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <br>
  <div >
   <%if user_signed_in? && current_user.admin?%>
    <%= link_to 'Edit', edit_product_path(@product), class:'btn btn-primary' %>
    <%end%>
    <%= link_to 'Back', root_path, class:'btn btn-warning' %>
    <%= link_to 'Add Cart', line_items_path(product_id: @product), class: "btn btn-success" %>
   </div>