config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  
  resources :carts do 
    post :terminar
  end

  scope "/admin" do
    resources :products
  end
  
  devise_for :users
  get "admin",to: "backoffice#index"
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<!--<Button tienda> -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a href="<%=root_path%>" class="navbar-brand">Tienda</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">

    <!--<Button Products> -->
    
      <%if user_signed_in? && current_user.admin?%>
        <li class="nav-item">
          <a class="btn btn-secondary" href="<%= products_path %>">Products
            <i class="fa-solid fa-mobile-button"></i>
          </a>
        </li>
      <% end %>

      <%if user_signed_in? && current_user.admin?%>
        <li class="nav-item mx-3">
          <a class="btn btn-secondary" href="<%= admin_path %>">Admin
            <i class="fa-solid fa-screwdriver-wrench"></i>
          </a>
        </li>
      <% end %>


      </ul>
    </div>
    </ul>
      <li>

    <!--<Carrito>--->

        <%if cart_has_items %>
          <%= link_to cart_path(@cart), class: "navbar-item btn btn-warning mx-3" do%>
            <span class ="icon-sm">
              <i class="fa-solid fa-cart-shopping"></i>
              <%= cart_count_over_one %>
            </span>
          <% end %>
        <% end %>
      </li>

    <!--<Users> -->

    <%if (user_signed_in?) %>
      <div class="btn-group dropstart">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="true">
        <%=  current_user.present? ? (current_user.email) : 'Ingresar' %>
          <i class="fa-solid fa-circle-user"></i> 
        </button>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item"><%= link_to "Editar", edit_user_registration_path, class:'dropdown-item' %></a></li>
          <li><a class="dropdown-item"><%= link_to 'Desconectarse', destroy_user_session_path , method: :delete, data: { confirm: 'Are you sure?' }, class:'dropdown-item'%></a></li>
        </ul> 
      </div>
    <%else %>
      <div class="btn-group dropstart">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <%=  current_user.present? ? (current_user.email) : 'Ingresar' %>
          <i class="fa-solid fa-circle-user"></i> 
        </button>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="<%= new_user_session_path%>">Conectarse</a></li>
        </ul> 
      </div>
    <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <%= favicon_link_tag 'tienda123.jpg' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/5d018e5526.js" crossorigin="anonymous"></script>
    <title>Tienda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
  <div class= "container-fluid">
    <%= yield %>
  </div>
  </body>
</html>